export type ParseResult =
  | { ok: true; model: ThreatModel }
  | { ok: false; error: string };

export interface ThreatModel {
  meta: ModelMeta;
  surfaces: DrawingSurface[];
  threats: Threat[];
  warnings: ParseWarning[];
}

export interface ModelMeta {
  threatModelName: string;
  owner: string;
  reviewer: string;
  contributors: string;
  assumptions: string;
  externalDependencies: string;
  highLevelSystemDescription: string;
  threatModelVersion: string;
}

export interface DrawingSurface {
  guid: string;
  name: string;
  borders: BorderElement[];
  lines: LineElement[];
}

export type BorderKind =
  | "StencilEllipse"
  | "StencilRectangle"
  | "StencilParallelLines"
  | "BorderBoundary"
  | "Unknown";

export interface BorderElement {
  kind: BorderKind;
  xsiType: string;
  guid: string;
  genericTypeId: string;
  name: string;
  position: Rect;
  outOfScope: boolean;
  properties: Record<string, string>;
  stroke?: { thickness: number; dashArray: string };
}

export type LineKind = "Connector" | "LineBoundary";

export interface LineElement {
  kind: LineKind;
  guid: string;
  genericTypeId: string;
  name: string;
  sourceGuid?: string;
  targetGuid?: string;
  portSource?: string;
  portTarget?: string;
  source: Point;
  target: Point;
  handle: Point;
  properties: Record<string, string>;
}

export type ThreatState =
  | "NotStarted"
  | "Mitigated"
  | "NeedsInvestigation"
  | "NotApplicable"
  | "AutoGenerated";

export type ThreatPriority = "High" | "Medium" | "Low" | "Unknown";

export interface Threat {
  id: number;
  surfaceGuid: string;
  flowGuid: string;
  sourceGuid?: string;
  targetGuid?: string;
  priority: ThreatPriority;
  state?: ThreatState;
  title: string;
  category: string;
  shortDescription: string;
  description: string;
  possibleMitigations: string;
  sdlPhase: string;
  properties: Record<string, string>;
}

export type ParseWarningKind =
  | "unknown-xsi-type"
  | "missing-field"
  | "malformed-interaction-key";

export interface ParseWarning {
  kind: ParseWarningKind;
  message: string;
  path?: string;
}

export interface Rect {
  left: number;
  top: number;
  width: number;
  height: number;
}

export interface Point {
  x: number;
  y: number;
}
