import { describe, expect, it } from "vitest";
import type { ParseWarning } from "./model";
import { parseThreats } from "./tm7-parse-threats";
import { parseXml } from "./xml-helpers";
import { loadExampleXml } from "../test-utils/load-fixture";

const NS_TM = "http://schemas.datacontract.org/2004/07/ThreatModeling.Model";
const NS_ARR = "http://schemas.microsoft.com/2003/10/Serialization/Arrays";
const NS_KB = "http://schemas.datacontract.org/2004/07/ThreatModeling.KnowledgeBase";
const NS_XSI = "http://www.w3.org/2001/XMLSchema-instance";

function wrap(inner: string): Document {
  const xml = `<ThreatModel xmlns="${NS_TM}"
                xmlns:a="${NS_ARR}"
                xmlns:b="${NS_KB}"
                xmlns:i="${NS_XSI}">${inner}</ThreatModel>`;
  const { doc, error } = parseXml(xml);
  if (error) throw new Error(error);
  return doc;
}

function threatEntry(opts: {
  id: number;
  surface: string;
  flow: string;
  source: string;
  target: string;
  priority?: string;
  state?: string | null; // null => nil
  properties?: Record<string, string>;
  omitSourceGuid?: boolean;
  interactionKey?: string;
}): string {
  const interactionKey =
    opts.interactionKey ?? `${opts.source}:${opts.flow}:${opts.target}`;
  const stateXml =
    opts.state === null
      ? `<b:State i:nil="true"/>`
      : opts.state !== undefined
        ? `<b:State>${opts.state}</b:State>`
        : "";
  const props = Object.entries(opts.properties ?? {})
    .map(
      ([k, v]) =>
        `<a:KeyValueOfstringstring><a:Key>${k}</a:Key><a:Value>${v}</a:Value></a:KeyValueOfstringstring>`,
    )
    .join("");
  return `
    <a:KeyValueOfstringThreatpc_P0_PhOB>
      <a:Key>TH${opts.id}${opts.source}${opts.flow}${opts.target}</a:Key>
      <a:Value>
        <b:DrawingSurfaceGuid>${opts.surface}</b:DrawingSurfaceGuid>
        <b:FlowGuid>${opts.flow}</b:FlowGuid>
        <b:Id>${opts.id}</b:Id>
        <b:InteractionKey>${interactionKey}</b:InteractionKey>
        <b:Priority>${opts.priority ?? "High"}</b:Priority>
        <b:Properties>${props}</b:Properties>
        ${opts.omitSourceGuid ? "" : `<b:SourceGuid>${opts.source}</b:SourceGuid>`}
        ${stateXml}
        <b:TargetGuid>${opts.target}</b:TargetGuid>
      </a:Value>
    </a:KeyValueOfstringThreatpc_P0_PhOB>`;
}

describe("parseThreats", () => {
  it("returns [] when ThreatInstances is missing", () => {
    const warnings: ParseWarning[] = [];
    expect(parseThreats(wrap(""), warnings)).toEqual([]);
    expect(warnings).toEqual([]);
  });

  it("parses a single threat with all typed fields + properties bag", () => {
    const doc = wrap(`<ThreatInstances>${threatEntry({
      id: 7,
      surface: "S",
      flow: "F",
      source: "A",
      target: "B",
      priority: "Medium",
      state: "AutoGenerated",
      properties: {
        Title: "T",
        UserThreatCategory: "Spoofing",
        UserThreatShortDescription: "short",
        UserThreatDescription: "long",
        PossibleMitigations: "mit",
        SDLPhase: "Design",
        Custom: "x",
      },
    })}</ThreatInstances>`);
    const warnings: ParseWarning[] = [];
    const threats = parseThreats(doc, warnings);
    expect(threats).toHaveLength(1);
    expect(threats[0]).toMatchObject({
      id: 7,
      surfaceGuid: "S",
      flowGuid: "F",
      sourceGuid: "A",
      targetGuid: "B",
      priority: "Medium",
      state: "AutoGenerated",
      title: "T",
      category: "Spoofing",
      shortDescription: "short",
      description: "long",
      possibleMitigations: "mit",
      sdlPhase: "Design",
    });
    expect(threats[0].properties["Custom"]).toBe("x");
    expect(warnings).toEqual([]);
  });

  it("leaves state undefined when <b:State i:nil> and emits no warning", () => {
    const doc = wrap(`<ThreatInstances>${threatEntry({
      id: 1,
      surface: "S",
      flow: "F",
      source: "A",
      target: "B",
      state: null,
    })}</ThreatInstances>`);
    const warnings: ParseWarning[] = [];
    const [t] = parseThreats(doc, warnings);
    expect(t.state).toBeUndefined();
    expect(warnings).toEqual([]);
  });

  it("maps unknown Priority to 'Unknown'", () => {
    const doc = wrap(`<ThreatInstances>${threatEntry({
      id: 1,
      surface: "S",
      flow: "F",
      source: "A",
      target: "B",
      priority: "Critical",
    })}</ThreatInstances>`);
    const warnings: ParseWarning[] = [];
    const [t] = parseThreats(doc, warnings);
    expect(t.priority).toBe("Unknown");
  });

  it("falls back to InteractionKey when SourceGuid is missing", () => {
    const doc = wrap(`<ThreatInstances>${threatEntry({
      id: 1,
      surface: "S",
      flow: "F",
      source: "src-guid",
      target: "tgt-guid",
      omitSourceGuid: true,
    })}</ThreatInstances>`);
    const warnings: ParseWarning[] = [];
    const [t] = parseThreats(doc, warnings);
    expect(t.sourceGuid).toBe("src-guid");
    expect(t.targetGuid).toBe("tgt-guid");
    expect(warnings).toEqual([]);
  });

  it("emits malformed-interaction-key warning when format is wrong and source missing", () => {
    const doc = wrap(`<ThreatInstances>${threatEntry({
      id: 1,
      surface: "S",
      flow: "F",
      source: "A",
      target: "B",
      omitSourceGuid: true,
      interactionKey: "not-three-parts",
    })}</ThreatInstances>`);
    const warnings: ParseWarning[] = [];
    const [t] = parseThreats(doc, warnings);
    expect(t.sourceGuid).toBeUndefined();
    expect(warnings).toHaveLength(1);
    expect(warnings[0].kind).toBe("malformed-interaction-key");
  });

  it("integration: real fixture parses 85 threats, all AutoGenerated, 0 warnings", () => {
    const { doc, error } = parseXml(loadExampleXml());
    expect(error).toBeNull();
    const warnings: ParseWarning[] = [];
    const threats = parseThreats(doc, warnings);
    expect(threats).toHaveLength(85);
    expect(warnings).toEqual([]);

    // Every threat has surface, flow, source, target, title, category
    for (const t of threats) {
      expect(t.surfaceGuid).toBeTruthy();
      expect(t.flowGuid).toBeTruthy();
      expect(t.sourceGuid).toBeTruthy();
      expect(t.targetGuid).toBeTruthy();
      expect(t.title).toBeTruthy();
      expect(t.category).toBeTruthy();
    }

    // At least one High-priority threat exists
    expect(threats.some((t) => t.priority === "High")).toBe(true);

    // States in this file are all AutoGenerated (per fixture)
    const states = new Set(threats.map((t) => t.state));
    expect(states).toEqual(new Set(["AutoGenerated"]));
  });
});
