import type { ParseWarning, Threat, ThreatState } from "./model";
import { NS_ARR, NS_KB, NS_TM, NS_XSI } from "./xml-helpers";

const KNOWN_PRIORITIES = new Set(["High", "Medium", "Low"]);
const KNOWN_STATES: ReadonlySet<ThreatState> = new Set([
  "NotStarted",
  "Mitigated",
  "NeedsInvestigation",
  "NotApplicable",
  "AutoGenerated",
]);

export function parseThreats(doc: Document, warnings: ParseWarning[]): Threat[] {
  const container = doc.getElementsByTagNameNS(NS_TM, "ThreatInstances")[0];
  if (!container) return [];

  const entries = container.children;
  const threats: Threat[] = [];

  for (let i = 0; i < entries.length; i++) {
    const entry = entries[i];
    // Iterate KeyValueOf* entries (we don't know the exact suffix; match by NS_ARR + startsWith)
    if (entry.namespaceURI !== NS_ARR) continue;
    if (!entry.localName.startsWith("KeyValueOf")) continue;

    const valueEl = childNs(entry, NS_ARR, "Value");
    if (!valueEl) continue;

    const threat = parseThreatValue(valueEl, warnings);
    if (threat) threats.push(threat);
  }

  return threats;
}

function parseThreatValue(value: Element, warnings: ParseWarning[]): Threat | null {
  const idText = readKb(value, "Id");
  const id = Number(idText);
  if (!Number.isFinite(id)) {
    warnings.push({
      kind: "missing-field",
      message: `Threat with non-numeric Id "${idText}" skipped`,
    });
    return null;
  }

  const surfaceGuid = readKb(value, "DrawingSurfaceGuid");
  const flowGuid = readKb(value, "FlowGuid");
  const interactionKey = readKb(value, "InteractionKey");

  let sourceGuid: string | undefined = readKbOrUndef(value, "SourceGuid");
  let targetGuid: string | undefined = readKbOrUndef(value, "TargetGuid");

  if ((!sourceGuid || !targetGuid) && interactionKey) {
    const parts = interactionKey.split(":");
    if (parts.length === 3) {
      sourceGuid = sourceGuid ?? parts[0];
      targetGuid = targetGuid ?? parts[2];
    } else {
      warnings.push({
        kind: "malformed-interaction-key",
        message: `Threat ${id}: expected "source:flow:target", got "${interactionKey}"`,
      });
    }
  }

  const priorityRaw = readKb(value, "Priority");
  const priority = KNOWN_PRIORITIES.has(priorityRaw)
    ? (priorityRaw as Threat["priority"])
    : "Unknown";

  const stateRaw = readKbOrUndef(value, "State");
  let state: ThreatState | undefined;
  if (stateRaw) {
    if (KNOWN_STATES.has(stateRaw as ThreatState)) {
      state = stateRaw as ThreatState;
    } else {
      warnings.push({
        kind: "missing-field",
        message: `Threat ${id}: unknown state "${stateRaw}"`,
      });
    }
  }

  const properties = collectThreatProperties(value);

  return {
    id,
    surfaceGuid,
    flowGuid,
    sourceGuid,
    targetGuid,
    priority,
    state,
    title: properties["Title"] ?? "",
    category: properties["UserThreatCategory"] ?? "",
    shortDescription: properties["UserThreatShortDescription"] ?? "",
    description: properties["UserThreatDescription"] ?? "",
    possibleMitigations: properties["PossibleMitigations"] ?? "",
    sdlPhase: properties["SDLPhase"] ?? "",
    properties,
  };
}

function collectThreatProperties(value: Element): Record<string, string> {
  const propsContainer = childNs(value, NS_KB, "Properties");
  if (!propsContainer) return {};
  const out: Record<string, string> = {};
  const pairs = propsContainer.getElementsByTagNameNS(NS_ARR, "KeyValueOfstringstring");
  for (let i = 0; i < pairs.length; i++) {
    const key = childNs(pairs[i], NS_ARR, "Key")?.textContent?.trim() ?? "";
    const val = childNs(pairs[i], NS_ARR, "Value")?.textContent ?? "";
    if (key) out[key] = val;
  }
  return out;
}

function childNs(parent: Element, ns: string, localName: string): Element | null {
  for (let i = 0; i < parent.children.length; i++) {
    const c = parent.children[i];
    if (c.localName === localName && c.namespaceURI === ns) return c;
  }
  return null;
}

function readKb(value: Element, localName: string): string {
  const el = childNs(value, NS_KB, localName);
  if (!el) return "";
  if (el.getAttributeNS(NS_XSI, "nil") === "true") return "";
  return el.textContent?.trim() ?? "";
}

function readKbOrUndef(value: Element, localName: string): string | undefined {
  const el = childNs(value, NS_KB, localName);
  if (!el) return undefined;
  if (el.getAttributeNS(NS_XSI, "nil") === "true") return undefined;
  const text = el.textContent?.trim();
  return text ? text : undefined;
}
