import type { ThreatPriority, ThreatState } from "../../domain/model";

const PRIORITY_CLASSES: Record<ThreatPriority, string> = {
  High: "bg-red-100 text-red-800 dark:bg-red-950/50 dark:text-red-200",
  Medium: "bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-200",
  Low: "bg-blue-100 text-blue-800 dark:bg-blue-950/50 dark:text-blue-200",
  Unknown: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300",
};

const STATE_CLASSES: Partial<Record<ThreatState, string>> = {
  Mitigated: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-200",
  NeedsInvestigation: "bg-yellow-100 text-yellow-800 dark:bg-yellow-950/50 dark:text-yellow-200",
  NotApplicable: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300",
  NotStarted: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300",
  AutoGenerated: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300",
};

export function PriorityBadge({ priority }: { priority: ThreatPriority }) {
  return (
    <span
      className={
        "inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium " +
        PRIORITY_CLASSES[priority]
      }
      data-testid="priority-badge"
    >
      {priority}
    </span>
  );
}

export function StateBadge({ state }: { state?: ThreatState }) {
  if (!state) return null;
  return (
    <span
      className={
        "inline-flex items-center rounded-full px-2 py-0.5 text-xs " +
        (STATE_CLASSES[state] ?? "bg-slate-100 text-slate-700")
      }
      data-testid="state-badge"
    >
      {state}
    </span>
  );
}

export function CategoryBadge({ category }: { category: string }) {
  return (
    <span
      className="inline-flex items-center rounded-full bg-slate-200 px-2 py-0.5 text-xs text-slate-700 dark:bg-slate-700 dark:text-slate-200"
      data-testid="category-badge"
    >
      {category}
    </span>
  );
}
